### ISSUE TITLE
POST to https://httpstat.us/302 returns 200

### ISSUE THREAD

**Issue by robert-mchugh** [aaronpowell/httpstatus#117]
GET'ing the endpoint returns 302 like it should. POSTing to it returns a 200; it should return a 302.

![image](https://user-images.githubusercontent.com/58016233/201460379-146f39b1-b3d9-4a2b-a3dc-d130777696c0.png)

**Comment by aaronpowell** [comment]
Postman, by default, will follow 3xx headers, and since the `302` returns a `Location` header that points to `https://httpstat.us`, it'll follow that and get the home page, which returns a `200` response.

If you go into _Settings_ on the request, you can disable this behaviour:

![Disable 3xx redirect follow](https://user-images.githubusercontent.com/434140/201549517-e04567ed-0bc6-4993-a8d9-67505c402f9b.png)

Here's a POST request done using `cURL`:

```
❯ curl -X POST -v https://httpstat.us/302
> POST /302 HTTP/1.1
> Host: httpstat.us
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Content-Length: 9
< Content-Type: text/plain
< Date: Sun, 13 Nov 2022 23:11:01 GMT
< Server: Kestrel
< Location: https://httpstat.us
< Set-Cookie: ARRAffinity=8704f50f7b5106506d91f9a9bf4b765528533ff3a17e44c2bee3d021b099959c;Path=/;HttpOnly;Secure;Domain=httpstat.us
< Set-Cookie: ARRAffinitySameSite=8704f50f7b5106506d91f9a9bf4b765528533ff3a17e44c2bee3d021b099959c;Path=/;HttpOnly;SameSite=None;Secure;Domain=httpstat.us
< Request-Context: appId=cid-v1:3548b0f5-7f75-492f-82bb-b6eb0e864e53
< Strict-Transport-Security: max-age=2592000
*
```

**Comment by robert-mchugh** [comment]
You were right, thanks for your help!
